// Auto-generated. Do not edit!

// (in-package albert_skills.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LookForItemFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.product_name = null;
    }
    else {
      if (initObj.hasOwnProperty('product_name')) {
        this.product_name = initObj.product_name
      }
      else {
        this.product_name = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LookForItemFeedback
    // Serialize message field [product_name]
    bufferOffset = _serializer.string(obj.product_name, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LookForItemFeedback
    let len;
    let data = new LookForItemFeedback(null);
    // Deserialize message field [product_name]
    data.product_name = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.product_name.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'albert_skills/LookForItemFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '43c214cbd68be8e1dc94727572e25071';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    string product_name
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LookForItemFeedback(null);
    if (msg.product_name !== undefined) {
      resolved.product_name = msg.product_name;
    }
    else {
      resolved.product_name = ''
    }

    return resolved;
    }
};

module.exports = LookForItemFeedback;
