; Auto-generated. Do not edit!


(cl:in-package albert_skills-msg)


;//! \htmlinclude LookForItemGoal.msg.html

(cl:defclass <LookForItemGoal> (roslisp-msg-protocol:ros-message)
  ((product_name
    :reader product_name
    :initarg :product_name
    :type cl:string
    :initform ""))
)

(cl:defclass LookForItemGoal (<LookForItemGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookForItemGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookForItemGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_skills-msg:<LookForItemGoal> is deprecated: use albert_skills-msg:LookForItemGoal instead.")))

(cl:ensure-generic-function 'product_name-val :lambda-list '(m))
(cl:defmethod product_name-val ((m <LookForItemGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader albert_skills-msg:product_name-val is deprecated.  Use albert_skills-msg:product_name instead.")
  (product_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookForItemGoal>) ostream)
  "Serializes a message object of type '<LookForItemGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'product_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'product_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookForItemGoal>) istream)
  "Deserializes a message object of type '<LookForItemGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'product_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'product_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookForItemGoal>)))
  "Returns string type for a message object of type '<LookForItemGoal>"
  "albert_skills/LookForItemGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookForItemGoal)))
  "Returns string type for a message object of type 'LookForItemGoal"
  "albert_skills/LookForItemGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookForItemGoal>)))
  "Returns md5sum for a message object of type '<LookForItemGoal>"
  "43c214cbd68be8e1dc94727572e25071")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookForItemGoal)))
  "Returns md5sum for a message object of type 'LookForItemGoal"
  "43c214cbd68be8e1dc94727572e25071")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookForItemGoal>)))
  "Returns full string definition for message of type '<LookForItemGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string product_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookForItemGoal)))
  "Returns full string definition for message of type 'LookForItemGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string product_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookForItemGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'product_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookForItemGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LookForItemGoal
    (cl:cons ':product_name (product_name msg))
))
