; Auto-generated. Do not edit!


(cl:in-package albert_skills-msg)


;//! \htmlinclude LookForItemResult.msg.html

(cl:defclass <LookForItemResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass LookForItemResult (<LookForItemResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookForItemResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookForItemResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_skills-msg:<LookForItemResult> is deprecated: use albert_skills-msg:LookForItemResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <LookForItemResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader albert_skills-msg:success-val is deprecated.  Use albert_skills-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookForItemResult>) ostream)
  "Serializes a message object of type '<LookForItemResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookForItemResult>) istream)
  "Deserializes a message object of type '<LookForItemResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookForItemResult>)))
  "Returns string type for a message object of type '<LookForItemResult>"
  "albert_skills/LookForItemResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookForItemResult)))
  "Returns string type for a message object of type 'LookForItemResult"
  "albert_skills/LookForItemResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookForItemResult>)))
  "Returns md5sum for a message object of type '<LookForItemResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookForItemResult)))
  "Returns md5sum for a message object of type 'LookForItemResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookForItemResult>)))
  "Returns full string definition for message of type '<LookForItemResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookForItemResult)))
  "Returns full string definition for message of type 'LookForItemResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookForItemResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookForItemResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LookForItemResult
    (cl:cons ':success (success msg))
))
