; Auto-generated. Do not edit!


(cl:in-package albert_skills-msg)


;//! \htmlinclude PickFeedback.msg.html

(cl:defclass <PickFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PickFeedback (<PickFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_skills-msg:<PickFeedback> is deprecated: use albert_skills-msg:PickFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickFeedback>) ostream)
  "Serializes a message object of type '<PickFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickFeedback>) istream)
  "Deserializes a message object of type '<PickFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickFeedback>)))
  "Returns string type for a message object of type '<PickFeedback>"
  "albert_skills/PickFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickFeedback)))
  "Returns string type for a message object of type 'PickFeedback"
  "albert_skills/PickFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickFeedback>)))
  "Returns md5sum for a message object of type '<PickFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickFeedback)))
  "Returns md5sum for a message object of type 'PickFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickFeedback>)))
  "Returns full string definition for message of type '<PickFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickFeedback)))
  "Returns full string definition for message of type 'PickFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PickFeedback
))
