; Auto-generated. Do not edit!


(cl:in-package albert_skills-msg)


;//! \htmlinclude PlaceGoal.msg.html

(cl:defclass <PlaceGoal> (roslisp-msg-protocol:ros-message)
  ((goal_id
    :reader goal_id
    :initarg :goal_id
    :type cl:string
    :initform ""))
)

(cl:defclass PlaceGoal (<PlaceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlaceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlaceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_skills-msg:<PlaceGoal> is deprecated: use albert_skills-msg:PlaceGoal instead.")))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <PlaceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader albert_skills-msg:goal_id-val is deprecated.  Use albert_skills-msg:goal_id instead.")
  (goal_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlaceGoal>) ostream)
  "Serializes a message object of type '<PlaceGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_id))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_id))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlaceGoal>) istream)
  "Deserializes a message object of type '<PlaceGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_id) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_id) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlaceGoal>)))
  "Returns string type for a message object of type '<PlaceGoal>"
  "albert_skills/PlaceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlaceGoal)))
  "Returns string type for a message object of type 'PlaceGoal"
  "albert_skills/PlaceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlaceGoal>)))
  "Returns md5sum for a message object of type '<PlaceGoal>"
  "1390c9c033b60649917fd23f66f91703")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlaceGoal)))
  "Returns md5sum for a message object of type 'PlaceGoal"
  "1390c9c033b60649917fd23f66f91703")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlaceGoal>)))
  "Returns full string definition for message of type '<PlaceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%#int32 product_id~%string goal_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlaceGoal)))
  "Returns full string definition for message of type 'PlaceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%#int32 product_id~%string goal_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlaceGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal_id))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlaceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PlaceGoal
    (cl:cons ':goal_id (goal_id msg))
))
