; Auto-generated. Do not edit!


(cl:in-package albert_skills-msg)


;//! \htmlinclude PlaceFeedback.msg.html

(cl:defclass <PlaceFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlaceFeedback (<PlaceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlaceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlaceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_skills-msg:<PlaceFeedback> is deprecated: use albert_skills-msg:PlaceFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlaceFeedback>) ostream)
  "Serializes a message object of type '<PlaceFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlaceFeedback>) istream)
  "Deserializes a message object of type '<PlaceFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlaceFeedback>)))
  "Returns string type for a message object of type '<PlaceFeedback>"
  "albert_skills/PlaceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlaceFeedback)))
  "Returns string type for a message object of type 'PlaceFeedback"
  "albert_skills/PlaceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlaceFeedback>)))
  "Returns md5sum for a message object of type '<PlaceFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlaceFeedback)))
  "Returns md5sum for a message object of type 'PlaceFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlaceFeedback>)))
  "Returns full string definition for message of type '<PlaceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlaceFeedback)))
  "Returns full string definition for message of type 'PlaceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlaceFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlaceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlaceFeedback
))
