; Auto-generated. Do not edit!


(cl:in-package albert_decision_making-msg)


;//! \htmlinclude ActiveInferenceGoal.msg.html

(cl:defclass <ActiveInferenceGoal> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:string
    :initform "")
   (product_id
    :reader product_id
    :initarg :product_id
    :type cl:string
    :initform ""))
)

(cl:defclass ActiveInferenceGoal (<ActiveInferenceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActiveInferenceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActiveInferenceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_decision_making-msg:<ActiveInferenceGoal> is deprecated: use albert_decision_making-msg:ActiveInferenceGoal instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <ActiveInferenceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader albert_decision_making-msg:state-val is deprecated.  Use albert_decision_making-msg:state instead.")
  (state m))

(cl:ensure-generic-function 'product_id-val :lambda-list '(m))
(cl:defmethod product_id-val ((m <ActiveInferenceGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader albert_decision_making-msg:product_id-val is deprecated.  Use albert_decision_making-msg:product_id instead.")
  (product_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActiveInferenceGoal>) ostream)
  "Serializes a message object of type '<ActiveInferenceGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'state))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'state))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'product_id))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'product_id))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActiveInferenceGoal>) istream)
  "Deserializes a message object of type '<ActiveInferenceGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'state) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'state) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'product_id) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'product_id) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActiveInferenceGoal>)))
  "Returns string type for a message object of type '<ActiveInferenceGoal>"
  "albert_decision_making/ActiveInferenceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActiveInferenceGoal)))
  "Returns string type for a message object of type 'ActiveInferenceGoal"
  "albert_decision_making/ActiveInferenceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActiveInferenceGoal>)))
  "Returns md5sum for a message object of type '<ActiveInferenceGoal>"
  "4b01c6369ab93de108f2bbc20673afbd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActiveInferenceGoal)))
  "Returns md5sum for a message object of type 'ActiveInferenceGoal"
  "4b01c6369ab93de108f2bbc20673afbd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActiveInferenceGoal>)))
  "Returns full string definition for message of type '<ActiveInferenceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string state~%string product_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActiveInferenceGoal)))
  "Returns full string definition for message of type 'ActiveInferenceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string state~%string product_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActiveInferenceGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'state))
     4 (cl:length (cl:slot-value msg 'product_id))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActiveInferenceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ActiveInferenceGoal
    (cl:cons ':state (state msg))
    (cl:cons ':product_id (product_id msg))
))
