; Auto-generated. Do not edit!


(cl:in-package albert_decision_making-msg)


;//! \htmlinclude ActiveInferenceFeedback.msg.html

(cl:defclass <ActiveInferenceFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ActiveInferenceFeedback (<ActiveInferenceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActiveInferenceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActiveInferenceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_decision_making-msg:<ActiveInferenceFeedback> is deprecated: use albert_decision_making-msg:ActiveInferenceFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActiveInferenceFeedback>) ostream)
  "Serializes a message object of type '<ActiveInferenceFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActiveInferenceFeedback>) istream)
  "Deserializes a message object of type '<ActiveInferenceFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActiveInferenceFeedback>)))
  "Returns string type for a message object of type '<ActiveInferenceFeedback>"
  "albert_decision_making/ActiveInferenceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActiveInferenceFeedback)))
  "Returns string type for a message object of type 'ActiveInferenceFeedback"
  "albert_decision_making/ActiveInferenceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActiveInferenceFeedback>)))
  "Returns md5sum for a message object of type '<ActiveInferenceFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActiveInferenceFeedback)))
  "Returns md5sum for a message object of type 'ActiveInferenceFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActiveInferenceFeedback>)))
  "Returns full string definition for message of type '<ActiveInferenceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActiveInferenceFeedback)))
  "Returns full string definition for message of type 'ActiveInferenceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActiveInferenceFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActiveInferenceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ActiveInferenceFeedback
))
