; Auto-generated. Do not edit!


(cl:in-package albert_decision_making-msg)


;//! \htmlinclude ActiveInferenceResult.msg.html

(cl:defclass <ActiveInferenceResult> (roslisp-msg-protocol:ros-message)
  ((res
    :reader res
    :initarg :res
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ActiveInferenceResult (<ActiveInferenceResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActiveInferenceResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActiveInferenceResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name albert_decision_making-msg:<ActiveInferenceResult> is deprecated: use albert_decision_making-msg:ActiveInferenceResult instead.")))

(cl:ensure-generic-function 'res-val :lambda-list '(m))
(cl:defmethod res-val ((m <ActiveInferenceResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader albert_decision_making-msg:res-val is deprecated.  Use albert_decision_making-msg:res instead.")
  (res m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActiveInferenceResult>) ostream)
  "Serializes a message object of type '<ActiveInferenceResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'res) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActiveInferenceResult>) istream)
  "Deserializes a message object of type '<ActiveInferenceResult>"
    (cl:setf (cl:slot-value msg 'res) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActiveInferenceResult>)))
  "Returns string type for a message object of type '<ActiveInferenceResult>"
  "albert_decision_making/ActiveInferenceResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActiveInferenceResult)))
  "Returns string type for a message object of type 'ActiveInferenceResult"
  "albert_decision_making/ActiveInferenceResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActiveInferenceResult>)))
  "Returns md5sum for a message object of type '<ActiveInferenceResult>"
  "e27848a10f8e7e4030443887dfea101b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActiveInferenceResult)))
  "Returns md5sum for a message object of type 'ActiveInferenceResult"
  "e27848a10f8e7e4030443887dfea101b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActiveInferenceResult>)))
  "Returns full string definition for message of type '<ActiveInferenceResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool res~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActiveInferenceResult)))
  "Returns full string definition for message of type 'ActiveInferenceResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool res~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActiveInferenceResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActiveInferenceResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ActiveInferenceResult
    (cl:cons ':res (res msg))
))
