// Generated by gencpp from file albert_decision_making/ActiveInferenceGoal.msg
// DO NOT EDIT!


#ifndef ALBERT_DECISION_MAKING_MESSAGE_ACTIVEINFERENCEGOAL_H
#define ALBERT_DECISION_MAKING_MESSAGE_ACTIVEINFERENCEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace albert_decision_making
{
template <class ContainerAllocator>
struct ActiveInferenceGoal_
{
  typedef ActiveInferenceGoal_<ContainerAllocator> Type;

  ActiveInferenceGoal_()
    : state()
    , product_id()  {
    }
  ActiveInferenceGoal_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , product_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _product_id_type;
  _product_id_type product_id;





  typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ActiveInferenceGoal_

typedef ::albert_decision_making::ActiveInferenceGoal_<std::allocator<void> > ActiveInferenceGoal;

typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceGoal > ActiveInferenceGoalPtr;
typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceGoal const> ActiveInferenceGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator1> & lhs, const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.product_id == rhs.product_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator1> & lhs, const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace albert_decision_making

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b01c6369ab93de108f2bbc20673afbd";
  }

  static const char* value(const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b01c6369ab93de1ULL;
  static const uint64_t static_value2 = 0x08f2bbc20673afbdULL;
};

template<class ContainerAllocator>
struct DataType< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "albert_decision_making/ActiveInferenceGoal";
  }

  static const char* value(const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string state\n"
"string product_id\n"
;
  }

  static const char* value(const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.product_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActiveInferenceGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::albert_decision_making::ActiveInferenceGoal_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
    s << indent << "product_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.product_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALBERT_DECISION_MAKING_MESSAGE_ACTIVEINFERENCEGOAL_H
