// Generated by gencpp from file albert_decision_making/ActiveInferenceFeedback.msg
// DO NOT EDIT!


#ifndef ALBERT_DECISION_MAKING_MESSAGE_ACTIVEINFERENCEFEEDBACK_H
#define ALBERT_DECISION_MAKING_MESSAGE_ACTIVEINFERENCEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace albert_decision_making
{
template <class ContainerAllocator>
struct ActiveInferenceFeedback_
{
  typedef ActiveInferenceFeedback_<ContainerAllocator> Type;

  ActiveInferenceFeedback_()
    {
    }
  ActiveInferenceFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ActiveInferenceFeedback_

typedef ::albert_decision_making::ActiveInferenceFeedback_<std::allocator<void> > ActiveInferenceFeedback;

typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceFeedback > ActiveInferenceFeedbackPtr;
typedef boost::shared_ptr< ::albert_decision_making::ActiveInferenceFeedback const> ActiveInferenceFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace albert_decision_making

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "albert_decision_making/ActiveInferenceFeedback";
  }

  static const char* value(const ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
;
  }

  static const char* value(const ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActiveInferenceFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::albert_decision_making::ActiveInferenceFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ALBERT_DECISION_MAKING_MESSAGE_ACTIVEINFERENCEFEEDBACK_H
