// Generated by gencpp from file albert_decision_making/SymbolicPerception.msg
// DO NOT EDIT!


#ifndef ALBERT_DECISION_MAKING_MESSAGE_SYMBOLICPERCEPTION_H
#define ALBERT_DECISION_MAKING_MESSAGE_SYMBOLICPERCEPTION_H

#include <ros/service_traits.h>


#include <albert_decision_making/SymbolicPerceptionRequest.h>
#include <albert_decision_making/SymbolicPerceptionResponse.h>


namespace albert_decision_making
{

struct SymbolicPerception
{

typedef SymbolicPerceptionRequest Request;
typedef SymbolicPerceptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SymbolicPerception
} // namespace albert_decision_making


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::albert_decision_making::SymbolicPerception > {
  static const char* value()
  {
    return "4c08d451042cc2dddd0c5755ae03d4fe";
  }

  static const char* value(const ::albert_decision_making::SymbolicPerception&) { return value(); }
};

template<>
struct DataType< ::albert_decision_making::SymbolicPerception > {
  static const char* value()
  {
    return "albert_decision_making/SymbolicPerception";
  }

  static const char* value(const ::albert_decision_making::SymbolicPerception&) { return value(); }
};


// service_traits::MD5Sum< ::albert_decision_making::SymbolicPerceptionRequest> should match
// service_traits::MD5Sum< ::albert_decision_making::SymbolicPerception >
template<>
struct MD5Sum< ::albert_decision_making::SymbolicPerceptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::albert_decision_making::SymbolicPerception >::value();
  }
  static const char* value(const ::albert_decision_making::SymbolicPerceptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::albert_decision_making::SymbolicPerceptionRequest> should match
// service_traits::DataType< ::albert_decision_making::SymbolicPerception >
template<>
struct DataType< ::albert_decision_making::SymbolicPerceptionRequest>
{
  static const char* value()
  {
    return DataType< ::albert_decision_making::SymbolicPerception >::value();
  }
  static const char* value(const ::albert_decision_making::SymbolicPerceptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::albert_decision_making::SymbolicPerceptionResponse> should match
// service_traits::MD5Sum< ::albert_decision_making::SymbolicPerception >
template<>
struct MD5Sum< ::albert_decision_making::SymbolicPerceptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::albert_decision_making::SymbolicPerception >::value();
  }
  static const char* value(const ::albert_decision_making::SymbolicPerceptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::albert_decision_making::SymbolicPerceptionResponse> should match
// service_traits::DataType< ::albert_decision_making::SymbolicPerception >
template<>
struct DataType< ::albert_decision_making::SymbolicPerceptionResponse>
{
  static const char* value()
  {
    return DataType< ::albert_decision_making::SymbolicPerception >::value();
  }
  static const char* value(const ::albert_decision_making::SymbolicPerceptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALBERT_DECISION_MAKING_MESSAGE_SYMBOLICPERCEPTION_H
