// Generated by gencpp from file albert_decision_making/SymbolicPerceptionResponse.msg
// DO NOT EDIT!


#ifndef ALBERT_DECISION_MAKING_MESSAGE_SYMBOLICPERCEPTIONRESPONSE_H
#define ALBERT_DECISION_MAKING_MESSAGE_SYMBOLICPERCEPTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32MultiArray.h>

namespace albert_decision_making
{
template <class ContainerAllocator>
struct SymbolicPerceptionResponse_
{
  typedef SymbolicPerceptionResponse_<ContainerAllocator> Type;

  SymbolicPerceptionResponse_()
    : observations()  {
    }
  SymbolicPerceptionResponse_(const ContainerAllocator& _alloc)
    : observations(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32MultiArray_<ContainerAllocator>  _observations_type;
  _observations_type observations;





  typedef boost::shared_ptr< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SymbolicPerceptionResponse_

typedef ::albert_decision_making::SymbolicPerceptionResponse_<std::allocator<void> > SymbolicPerceptionResponse;

typedef boost::shared_ptr< ::albert_decision_making::SymbolicPerceptionResponse > SymbolicPerceptionResponsePtr;
typedef boost::shared_ptr< ::albert_decision_making::SymbolicPerceptionResponse const> SymbolicPerceptionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator1> & lhs, const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.observations == rhs.observations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator1> & lhs, const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace albert_decision_making

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a8f37e92cf560cf92c704a0702bbfe6";
  }

  static const char* value(const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a8f37e92cf560cfULL;
  static const uint64_t static_value2 = 0x92c704a0702bbfe6ULL;
};

template<class ContainerAllocator>
struct DataType< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "albert_decision_making/SymbolicPerceptionResponse";
  }

  static const char* value(const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32MultiArray observations\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int32[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.observations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SymbolicPerceptionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::albert_decision_making::SymbolicPerceptionResponse_<ContainerAllocator>& v)
  {
    s << indent << "observations: ";
    s << std::endl;
    Printer< ::std_msgs::Int32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.observations);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALBERT_DECISION_MAKING_MESSAGE_SYMBOLICPERCEPTIONRESPONSE_H
